# Generated by Django 5.0.7 on 2024-08-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time_duration',
            field=models.CharField(max_length=255),
        ),
    ]
