# Generated by Django 5.0.7 on 2024-08-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_alter_course_time_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='batch_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_duration',
            field=models.DurationField(),
        ),
    ]
